table fact_monthly_incidents
	lineageTag: d7f76ce7-c149-4971-bcb6-65431c088d60

	column plant_code
		dataType: string
		lineageTag: 5ffaed04-6299-44b1-8674-f29900b587af
		summarizeBy: none
		sourceColumn: plant_code

		annotation SummarizationSetBy = Automatic

	column reporting_month
		dataType: dateTime
		formatString: General Date
		lineageTag: 5ac44bcc-84b6-4958-a615-228d51df26ba
		summarizeBy: none
		sourceColumn: reporting_month

		annotation SummarizationSetBy = Automatic

	column source_category
		dataType: string
		lineageTag: 761aa498-c3d2-4354-8eb4-1cb361c98392
		summarizeBy: none
		sourceColumn: source_category

		annotation SummarizationSetBy = Automatic

	column classification
		dataType: string
		lineageTag: c6e1a375-1ed1-4461-8fa5-49f02cd29a69
		summarizeBy: none
		sourceColumn: classification

		annotation SummarizationSetBy = Automatic

	column code_group
		dataType: string
		lineageTag: 2c99c95e-29bb-4f69-8122-defd97b6db86
		summarizeBy: none
		sourceColumn: code_group

		annotation SummarizationSetBy = Automatic

	column incident_count
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 474c2856-90da-4681-b3b1-0cff9d16f87b
		summarizeBy: sum
		sourceColumn: incident_count

		annotation SummarizationSetBy = Automatic

	partition fact_monthly_incidents = m
		mode: import
		queryGroup: 'Monthly Incidents'
		source =
				let
				    Sample = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rZsxaxtBEIX/ilHt4LuTLcdpQwpDCCncGRchcREIKhIV+fkRsvEF3eztfO8NqBBXfMw9ze7M21k9Pm6+fv7yMG0uN9MwDe+G8fh5GIYPp8/x6f3++88fz/vDn4v7jxfDeDVMp4eH59/7b7+OX18fjdPTJUPdXA27M9TLo4GQPv09vEV1/H4W1RajXqP6H/XyaFyiJlEqjCJStUlYqg6qKVUQ1VaT6oaSmkoF6dkmrSsV/HwdFFHqWlNqR0kkp9qkdaU4qqlU8PvdaErdUlJTqWDJtEl49XVQZKPaaUpdU1JTKRQTzqkOiqy+27rqt44iy69NwknVQZGkeq9JFbzfOoko1SZhpTooklR3ZUqtk0jxa5Nw8euggFLjUKVUhwRyaoVEN6oeChS/UWzTg6DELn25ZFZIdPX1UGCfGsUuPVBKbNJRTDin7CZ9PKHGuwLrl0X1l1+GlEyqNIpI5SZVltTf0jOk5JaeRhGlROcXBCU6vyg9VeuH3g9LJVq/QCrX+mVIOKls6zejROsXvJ9o/VBMHaU4q1/+ZpTo/YLt0/V+GRJefrb3m1Gi98Mksvxs65dGkZwSrR8mEaVs65dGkZxyrV+WRDYq2/qlUUAp1fotg1KtX7AP+94vjWpKtcxP1fsF7ye26YHoapseKGV7vxkltumB5u6AJkOiy6/K+xljP0zKKlUy9UujsjnlTP0oiShlD/3SKJJTovXDpGzxKxn6pVFEqRrnZwz9zotfydQvjcoWP2PqF7yfaP0C0VXrFyhV5PyMqV+guej8gtdTnR96PTR2MJzfSEnZsYPj/CaMyh6mG84vCEp0figmdJjuOL8gKtH5bSmJ5FTR0K/E+b2hbOeXJQGlqoZ+jvFbrpmioZ9h/JbZWTX0KzF+M8pt0rMkklNFQz/H+AVdkFv7siTSJai1j6OIUu6Flyypv/oyJGz87No3o2pOPY0LLygmnFNFp57GhZdldqq1b5kIcu1bii7XvkAp9XICJYF9qurQ07nwEvx+NXcTKi68ZEhYKbX2BZ21m1NZEunR7ZxKo0Dnad93yZJA51n1TwfnvkuQCe6hZ5ZEHLJ93SWNIqcu4qFnkJ3ioWeQCPZ1lzSKKCWeeQZBiWeeKCacU+qZZ/D7iWeeQVA1/3Qoue2SRq0o9fQP", BinaryEncoding.Base64), Compression.Deflate)), {"plant_code", "reporting_month", "source_category", "classification", "code_group", "incident_count"}),
				    Source = if DataFolder = "" then Sample else Table.PromoteHeaders(Excel.Workbook(File.Contents(DataFolder & "/fact_monthly_incidents.xlsx"), null, true){[Item="sheet1", Kind="Sheet"]}[Data], [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Source, {{"plant_code", type text}, {"reporting_month", type datetime}, {"source_category", type text}, {"classification", type text}, {"code_group", type text}, {"incident_count", Int64.Type}}, "en-GB")
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

